# Generated by Django 5.2.7 on 2025-11-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0002_billingdetails_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderItem',
        ),
    ]
