# Generated by Django 5.2.7 on 2025-11-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0003_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='checkapp.billingdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.product')),
            ],
        ),
    ]
